language: node_js

sudo: false

dist: trusty

node_js:
  - "10"

before_install:
  - npm install -g npm@latest

install:
  - npm install

script:
  - ng lint
  - ng build --prod --aot --buildOptimizer

git:
  depth: 1
